import type { ThemePackParams, ThemePreset } from './types'

/**
 * 预设主题列表
 */
export const presetThemes: ThemePreset[] = [
  {
      id: 'ios-light',
      name: 'iOS 亮色',
      description: '简洁优雅的苹果风格，柔和圆角与精致阴影',
      preview: '☀️',
      params: {
      themeName: 'ios-light',
      cardBg: '#ffffff',
      cardOpacity: 0.85,
      cardRadius: 16,
      cardShadow: 8,
      cardBorder: 'rgba(0,0,0,0.06)',
      cardBorderWidth: 0.5,
      cardBlur: 12,
      textColor: '#1d1d1f',
      titleColor: '#1d1d1f',
      groupTitleColor: '#86868b',
      searchBg: 'rgba(255,255,255,0.72)',
      searchColor: '#1d1d1f',
      searchRadius: 12,
      searchBorder: 'rgba(0,0,0,0.08)',
      floatBtnColor: 'rgba(0,0,0,0.35)',
      clockColor: '#1d1d1f',
      logoColor: '#1d1d1f',
      enableDarkMode: true,
      darkCardBg: '#1c1c1e',
      darkTextColor: '#f5f5f7'
      }
  },
  {
      id: 'ios-dark',
      name: 'iOS 暗色',
      description: '深邃沉稳的暗色模式，苹果风格的暗夜体验',
      preview: '🌙',
      params: {
      themeName: 'ios-dark',
      cardBg: '#1c1c1e',
      cardOpacity: 0.88,
      cardRadius: 16,
      cardShadow: 12,
      cardBorder: 'rgba(255,255,255,0.08)',
      cardBorderWidth: 0.5,
      cardBlur: 16,
      textColor: '#f5f5f7',
      titleColor: '#ffffff',
      groupTitleColor: '#98989d',
      searchBg: 'rgba(44,44,46,0.8)',
      searchColor: '#f5f5f7',
      searchRadius: 12,
      searchBorder: 'rgba(255,255,255,0.1)',
      floatBtnColor: 'rgba(255,255,255,0.15)',
      clockColor: '#f5f5f7',
      logoColor: '#ffffff',
      enableDarkMode: false,
      darkCardBg: '#1c1c1e',
      darkTextColor: '#f5f5f7'
      }
  },
  {
      id: 'black-gold',
      name: '黑金奢华',
      description: '金色点缀的深邃黑底，彰显尊贵科技感',
      preview: '✨',
      params: {
      themeName: 'black-gold',
      cardBg: '#1a1a1a',
      cardOpacity: 0.92,
      cardRadius: 12,
      cardShadow: 6,
      cardBorder: 'rgba(212,175,55,0.35)',
      cardBorderWidth: 1,
      cardBlur: 8,
      textColor: '#d4af37',
      titleColor: '#f0d060',
      groupTitleColor: '#b8960c',
      searchBg: 'rgba(26,26,26,0.85)',
      searchColor: '#d4af37',
      searchRadius: 10,
      searchBorder: 'rgba(212,175,55,0.4)',
      floatBtnColor: 'rgba(212,175,55,0.25)',
      clockColor: '#f0d060',
      logoColor: '#f0d060',
      enableDarkMode: false,
      darkCardBg: '#1a1a1a',
      darkTextColor: '#d4af37'
      }
  },
  {
      id: 'sakura-pink',
      name: '樱花粉',
      description: '甜美梦幻的粉色世界，轻柔温暖的少女风',
      preview: '🌸',
      params: {
      themeName: 'sakura-pink',
      cardBg: '#fff0f5',
      cardOpacity: 0.80,
      cardRadius: 18,
      cardShadow: 6,
      cardBorder: 'rgba(255,105,180,0.25)',
      cardBorderWidth: 1,
      cardBlur: 14,
      textColor: '#d6336c',
      titleColor: '#c2255c',
      groupTitleColor: '#f06595',
      searchBg: 'rgba(255,240,245,0.75)',
      searchColor: '#d6336c',
      searchRadius: 20,
      searchBorder: 'rgba(255,105,180,0.3)',
      floatBtnColor: 'rgba(255,105,180,0.4)',
      clockColor: '#c2255c',
      logoColor: '#c2255c',
      enableDarkMode: true,
      darkCardBg: '#2d1a24',
      darkTextColor: '#ffc0cb'
      }
  },
  {
      id: 'ocean-blue',
      name: '深海蓝',
      description: '宁静深远的海洋蓝调，清新通透的现代美学',
      preview: '🌊',
      params: {
      themeName: 'ocean-blue',
      cardBg: '#f0f7ff',
      cardOpacity: 0.82,
      cardRadius: 14,
      cardShadow: 8,
      cardBorder: 'rgba(59,130,246,0.15)',
      cardBorderWidth: 0.5,
      cardBlur: 12,
      textColor: '#1e3a5f',
      titleColor: '#1e40af',
      groupTitleColor: '#6b9bd2',
      searchBg: 'rgba(240,247,255,0.8)',
      searchColor: '#1e3a5f',
      searchRadius: 12,
      searchBorder: 'rgba(59,130,246,0.2)',
      floatBtnColor: 'rgba(37,99,235,0.4)',
      clockColor: '#1e40af',
      logoColor: '#1e40af',
      enableDarkMode: true,
      darkCardBg: '#0f1f3d',
      darkTextColor: '#bfdbfe'
      }
  },
  {
      id: 'glassmorphism',
      name: '毛玻璃',
      description: '极致透明的玻璃质感，前卫现代的视觉体验',
      preview: '💎',
      params: {
      themeName: 'glassmorphism',
      cardBg: '#ffffff',
      cardOpacity: 0.45,
      cardRadius: 20,
      cardShadow: 10,
      cardBorder: 'rgba(255,255,255,0.35)',
      cardBorderWidth: 1,
      cardBlur: 20,
      textColor: '#1a1a2e',
      titleColor: '#0f0f23',
      groupTitleColor: '#555580',
      searchBg: 'rgba(255,255,255,0.35)',
      searchColor: '#1a1a2e',
      searchRadius: 16,
      searchBorder: 'rgba(255,255,255,0.3)',
      floatBtnColor: 'rgba(255,255,255,0.2)',
      clockColor: '#0f0f23',
      logoColor: '#0f0f23',
      enableDarkMode: true,
      darkCardBg: '#0d0d0d',
      darkTextColor: '#e0e0e0'
      }
  },
  {
      id: 'forest-green',
      name: '森林绿',
      description: '生机盎然的自然色调，沉静优雅的有机美学',
      preview: '🌿',
      params: {
      themeName: 'forest-green',
      cardBg: '#f0f7f0',
      cardOpacity: 0.85,
      cardRadius: 14,
      cardShadow: 6,
      cardBorder: 'rgba(34,139,34,0.15)',
      cardBorderWidth: 0.5,
      cardBlur: 10,
      textColor: '#1a3a1a',
      titleColor: '#155724',
      groupTitleColor: '#6b9e6b',
      searchBg: 'rgba(240,247,240,0.78)',
      searchColor: '#1a3a1a',
      searchRadius: 12,
      searchBorder: 'rgba(34,139,34,0.18)',
      floatBtnColor: 'rgba(34,139,34,0.35)',
      clockColor: '#155724',
      logoColor: '#155724',
      enableDarkMode: true,
      darkCardBg: '#0f1f0f',
      darkTextColor: '#b8e6b8'
      }
  },
  {
      id: 'cyberpunk',
      name: '赛博朋克',
      description: '霓虹闪烁的未来都市，炫酷夺目的科技光影',
      preview: '🔮',
      params: {
      themeName: 'cyberpunk',
      cardBg: '#0a0a1a',
      cardOpacity: 0.90,
      cardRadius: 6,
      cardShadow: 0,
      cardBorder: 'rgba(0,255,255,0.4)',
      cardBorderWidth: 1,
      cardBlur: 6,
      textColor: '#00ffff',
      titleColor: '#ff00ff',
      groupTitleColor: '#00ff88',
      searchBg: 'rgba(10,10,26,0.85)',
      searchColor: '#00ffff',
      searchRadius: 4,
      searchBorder: 'rgba(255,0,255,0.5)',
      floatBtnColor: 'rgba(0,255,255,0.2)',
      clockColor: '#ff00ff',
      logoColor: '#00ffff',
      enableDarkMode: false,
      darkCardBg: '#0a0a1a',
      darkTextColor: '#00ffff'
      }
  }
]

/**
 * 根据ID获取预设主题
 */
export function getPresetTheme(id: string): ThemePreset | undefined {
  return presetThemes.find(t => t.id === id)
}
